PROJECT=Command_Line_Parser_Generator

GENERATED_EXECUTABLES=bin/$(LC_PROJECT)-run

GENERATED_SOURCES=$(HG_STATE_SOURCE) \
                  adacontrol \
                  ahven

SCRIPTS=

TEST_OUTPUT=tests/results

