#! /bin/bash
#-----------------------------------------------------------------------------

if cd "$(dirname "$0")" ; then
   true
else
   echo "Can not make '$(dirname "$0")' the current directory." 1>&2
   exit 100
fi

#-----------------------------------------------------------------------------

for source in ../../src/*.ad? ; do
   ln -fs "${source}" "bad_$(basename "${source}")"
done

#-----------------------------------------------------------------------------

rm -f errors

for package in bad_*.ads ; do
   ../../bin/parse_package < "${package}" \
     1>"${package}.log" \
     2>"${package}.errors"
   result=$?

   if [ ${result} -eq 0 ]; then
      echo "Parsed '${package}', even if it should have failed." >> errors
   else
      rm -f "${package}.log" \
            "${package}.errors"
   fi
done

#-----------------------------------------------------------------------------

if [ -f errors ]; then
   cat errors
   exit $(wc -l < errors ; rm -f errors)
fi

#-----------------------------------------------------------------------------
